/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/index.js",
    "./src/App.js",
    "./src/components/Navbar.js",
    "./src/components/ProfileCard.js",
    "./src/components/BusCard.js",
    "./src/components/BusDetails.js",
    "./src/components/BusSeats.js",
    "./src/components/SingleBus.js",
    "./src/components/NotFound.js",
    "./src/components/AdminTasks.js",
    "./src/components/AddBus.js",
    "./src/components/HistoryCard.js",
    "./src/components/UserHistory.js",
    "./src/components/CancelTicket.js",
    "./src/components/InfoCard.js",
    "./src/components/AllHistory.js",
    "./src/components/AllUsers.js",
    "./src/components/Location.js",
    "./src/components/Loader.js",
    "./src/components/SearchContainer.js",
    "./src/components/FilterContainer.js",
    "./src/components/SortContainer.js",
    "./src/pages/Home.js",
    "./src/pages/Login.js",
    "./src/pages/Register.js",
    "./src/pages/Users.js",
    "./src/pages/Booking.js",
    "./src/pages/NewBus.js",
    "./src/pages/History.js",
    "./src/pages/404Page.js"
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

